#!/bin/sh

#CURRENT_DIR=~/showtime_mod
CURRENT_DIR=$(pwd)
SHOWTIME_DIR=$HOME/showtime
[ -z $SHOWTIME_DIR ] && echo "Error: SHOWTIME_DIR undefined." && exit 1
[ -d $SHOWTIME_DIR ] || echo "Error: Showtime build directory $SHOWTIME_DIR not found." || exit 1

# clean previous build and custom font
echo "Cleaning previous builds..."
cd $SHOWTIME_DIR
find $SHOWTIME_DIR -name '*.d' | xargs rm 1>/dev/null
find $SHOWTIME_DIR/build.ps3/pkg -name '*.zip' | xargs rm 1>/dev/null
[ -e $SHOWTIME_DIR/build.ps3/config.mak ] && make clean
[ -e $SHOWTIME_DIR/support/font.ttf ] && rm $SHOWTIME_DIR/support/font.ttf
cd $CURRENT_DIR

# fetch latest codes
echo "Fetching latest codes..."
cd $SHOWTIME_DIR
git checkout .
git pull
cd $CURRENT_DIR

# reconfigure building environment
echo "Reconfiguring..."
cd $SHOWTIME_DIR
#./configure.ps3 --release --cleanbuild --ccache
cd $CURRENT_DIR

# patch cassine's modification: version string, OX key assignment, and font file
echo "Applying patches..."
patch $SHOWTIME_DIR/src/arch/ps3/ps3_main.c -p0 < $CURRENT_DIR/patches/ps3_main.c.patch
patch $SHOWTIME_DIR/support/getver.sh -p0 < $CURRENT_DIR/patches/getver.sh.patch
patch $SHOWTIME_DIR/src/ui/glw/glw_ps3.c -p0 < $CURRENT_DIR/patches/glw_ps3.c.patch
patch $SHOWTIME_DIR/support/ps3.mk -p0 < $CURRENT_DIR/patches/ps3.mk.patch

# remove garbage generated by patch
[ -e $SHOWTIME_DIR/src/arch/arch_ps3.c.orig ] && rm $SHOWTIME_DIR/src/arch/arch_ps3.c.orig
[ -e $SHOWTIME_DIR/src/arch/arch_ps3.c.rej ] && rm $SHOWTIME_DIR/src/arch/arch_ps3.c.rej
[ -e $SHOWTIME_DIR/support/getver.sh.orig ] && rm $SHOWTIME_DIR/support/getver.sh.orig
[ -e $SHOWTIME_DIR/support/getver.sh.rej ] && rm $SHOWTIME_DIR/support/getver.sh.rej
[ -e $SHOWTIME_DIR/src/ui/glw/glw_ps3.c.orig ] && rm $SHOWTIME_DIR/src/ui/glw/glw_ps3.c.orig
[ -e $SHOWTIME_DIR/src/ui/glw/glw_ps3.c.rej ] && rm $SHOWTIME_DIR/src/ui/glw/glw_ps3.c.rej
[ -e $SHOWTIME_DIR/support/ps3.mk.orig ] && rm $SHOWTIME_DIR/support/ps3.mk.orig
[ -e $SHOWTIME_DIR/support/ps3.mk.rej ] && rm $SHOWTIME_DIR/support/ps3.mk.rej

# remove previous builds
[ -d $SHOWTIME_DIR/build.ps3/dist ] && rm -rf $SHOWTIME_DIR/build.ps3/dist

# replace original Makefile by custom one, but this may be dangerous if 
# the author changes its structures, so use patches instead
# $CURRENT_DIR/support/ps3.mk will be reserved as template
#cp $CURRENT_DIR/support/ps3.mk $SHOWTIME_DIR/support

# copy custom font
cp $CURRENT_DIR/font/font.ttf $SHOWTIME_DIR/support

# check language file and copy
cd $SHOWTIME_DIR
support/update_lang.py $CURRENT_DIR/lang/*.lang
cd $CURRENT_DIR
cp $CURRENT_DIR/lang/*.lang $SHOWTIME_DIR/lang

# print current version string
printf "Building... showtime-"
$SHOWTIME_DIR/support/getver.sh $SHOWTIME_DIR

# fix wrong version string
# well, sometimes the version string desyncs due to unknown reasons. fix it manually if
# necessary
#$SHOWTIME_DIR/support/version.sh $SHOWTIME_DIR $SHOWTIME_DIR/build.ps3/buildversion.h

# configure with ccache to speed up compilation
cd $SHOWTIME_DIR
#./configure.ps3 --release --cleanbuild --ccache

# build and clean up
make -j4
make dist
make clean

# remove font to avoid spoiling local repo
rm $SHOWTIME_DIR/support/font.ttf

md5sum $SHOWTIME_DIR/build.ps3/dist/*

cd $CURRENT_DIR
